package models;
// Generated 05/09/2018 19:48:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tags generated by hbm2java
 */
public class Tags  implements java.io.Serializable {

    private String idTag;
    private String nomeTag;
    private Set<Posts> postsDaTag = new HashSet<Posts>(0);

    public Tags() {
    }
	
    public Tags(String idTag, String nomeTag) {
        this.idTag = idTag;
        this.nomeTag = nomeTag;
    }
    public Tags(String idTag, String nomeTag, Set<Posts> postsDaTag) {
       this.idTag = idTag;
       this.nomeTag = nomeTag;
       this.postsDaTag = postsDaTag;
    }
   
    public String getIdTag() {
        return this.idTag;
    }
    
    public void setIdTag(String idTag) {
        this.idTag = idTag;
    }
    public String getNomeTag() {
        return this.nomeTag;
    }
    
    public void setNomeTag(String nomeTag) {
        this.nomeTag = nomeTag;
    }
    
    public Set<Posts> getPostsDaTag() {
        return this.postsDaTag;
    }
    
    public void setPostsDaTag(Set<Posts> postsDaTag) {
        this.postsDaTag = postsDaTag;
    }

}


